@cdi-api-version@=1.2
@commons-logging-version@=1.2
@faces-spec-version@=2.3.2.JAKARTA-LIFERAY-PATCHED-1
@faces-api-version@=2.3.2.JAKARTA-LIFERAY-PATCHED-1
@gdk-version@=12.2.0-1-0
@httpclient-version@=4.5.13
@liferay-faces-alloy-version@=5.0.0
@liferay-faces-bridge-ext-version@=9.0.0
@liferay-faces-bridge-impl-version@=7.0.0
@liferay-faces-portal-version@=7.0.0
@mojarra-version@=2.3.21.LIFERAY-PATCHED-2.JAKARTA-LIFERAY-PATCHED-1
@primefaces-version@=15.0.6.LIFERAY-PATCHED-1.JAKARTA-LIFERAY-PATCHED-1
